//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexOrder {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Frm_C_Cart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Frm_C_Cart() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlexOrder.Frm_C_Cart", typeof(Frm_C_Cart).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [Font: Name=Microsoft YaHei UI, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False] に類似した型 System.Drawing.Font のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Font btnBack_Font {
            get {
                object obj = ResourceManager.GetObject("btnBack.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   {X=113,Y=648} に類似した型 System.Drawing.Point のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Point btnBack_Location {
            get {
                object obj = ResourceManager.GetObject("btnBack.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {Width=155, Height=87} に類似した型 System.Drawing.Size のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Size btnBack_Size {
            get {
                object obj = ResourceManager.GetObject("btnBack.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   1 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int btnBack_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnBack.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   btnBack に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnBack_Text {
            get {
                return ResourceManager.GetString("btnBack.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnDelete_HeaderText {
            get {
                return ResourceManager.GetString("btnDelete.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool btnDelete_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("btnDelete.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   80 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int btnDelete_Width {
            get {
                object obj = ResourceManager.GetObject("btnDelete.Width", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   [Font: Name=Microsoft YaHei UI, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False] に類似した型 System.Drawing.Font のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Font btnGoPay_Font {
            get {
                object obj = ResourceManager.GetObject("btnGoPay.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   {X=751,Y=648} に類似した型 System.Drawing.Point のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Point btnGoPay_Location {
            get {
                object obj = ResourceManager.GetObject("btnGoPay.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {Width=155, Height=87} に類似した型 System.Drawing.Size のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Size btnGoPay_Size {
            get {
                object obj = ResourceManager.GetObject("btnGoPay.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   1 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int btnGoPay_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnGoPay.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   btnGoPay に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnGoPay_Text {
            get {
                return ResourceManager.GetString("btnGoPay.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnMinus_HeaderText {
            get {
                return ResourceManager.GetString("btnMinus.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool btnMinus_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("btnMinus.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   80 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int btnMinus_Width {
            get {
                object obj = ResourceManager.GetObject("btnMinus.Width", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnPlus_HeaderText {
            get {
                return ResourceManager.GetString("btnPlus.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool btnPlus_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("btnPlus.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   80 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int btnPlus_Width {
            get {
                object obj = ResourceManager.GetObject("btnPlus.Width", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   [Font: Name=MS UI Gothic, Size=16, Units=3, GdiCharSet=1, GdiVerticalFont=False] に類似した型 System.Drawing.Font のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Font btnRestart_Font {
            get {
                object obj = ResourceManager.GetObject("btnRestart.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   {X=32,Y=12} に類似した型 System.Drawing.Point のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Point btnRestart_Location {
            get {
                object obj = ResourceManager.GetObject("btnRestart.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {Width=41, Height=39} に類似した型 System.Drawing.Size のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Size btnRestart_Size {
            get {
                object obj = ResourceManager.GetObject("btnRestart.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   5 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int btnRestart_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnRestart.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   ↺ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnRestart_Text {
            get {
                return ResourceManager.GetString("btnRestart.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {X=113,Y=12} に類似した型 System.Drawing.Point のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Point dgvCart_Location {
            get {
                object obj = ResourceManager.GetObject("dgvCart.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   51 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int dgvCart_RowHeadersWidth {
            get {
                object obj = ResourceManager.GetObject("dgvCart.RowHeadersWidth", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   {Width=793, Height=530} に類似した型 System.Drawing.Size のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Size dgvCart_Size {
            get {
                object obj = ResourceManager.GetObject("dgvCart.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   0 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int dgvCart_TabIndex {
            get {
                object obj = ResourceManager.GetObject("dgvCart.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string goods_id_HeaderText {
            get {
                return ResourceManager.GetString("goods_id.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool goods_id_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("goods_id.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   False に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool goods_id_Visible {
            get {
                object obj = ResourceManager.GetObject("goods_id.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   goods_name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string goods_name_HeaderText {
            get {
                return ResourceManager.GetString("goods_name.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int goods_name_MinimumWidth {
            get {
                object obj = ResourceManager.GetObject("goods_name.MinimumWidth", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool goods_name_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("goods_name.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   140 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int goods_name_Width {
            get {
                object obj = ResourceManager.GetObject("goods_name.Width", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   goods_price に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string goods_price_HeaderText {
            get {
                return ResourceManager.GetString("goods_price.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int goods_price_MinimumWidth {
            get {
                object obj = ResourceManager.GetObject("goods_price.MinimumWidth", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool goods_price_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("goods_price.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   140 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int goods_price_Width {
            get {
                object obj = ResourceManager.GetObject("goods_price.Width", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   img_goods_image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string img_goods_image_HeaderText {
            get {
                return ResourceManager.GetString("img_goods_image.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int img_goods_image_MinimumWidth {
            get {
                object obj = ResourceManager.GetObject("img_goods_image.MinimumWidth", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool img_goods_image_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("img_goods_image.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool lblConfirm1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblConfirm1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   NoControl に類似した型 System.Windows.Forms.ImeMode のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Windows.Forms.ImeMode lblConfirm1_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lblConfirm1.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   {X=21,Y=172} に類似した型 System.Drawing.Point のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Point lblConfirm1_Location {
            get {
                object obj = ResourceManager.GetObject("lblConfirm1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {Width=71, Height=12} に類似した型 System.Drawing.Size のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Size lblConfirm1_Size {
            get {
                object obj = ResourceManager.GetObject("lblConfirm1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   13 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int lblConfirm1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblConfirm1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   lblConfirm1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblConfirm1_Text {
            get {
                return ResourceManager.GetString("lblConfirm1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   False に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool lblConfirm1_Visible {
            get {
                object obj = ResourceManager.GetObject("lblConfirm1.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool lblConfirm2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblConfirm2.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   NoControl に類似した型 System.Windows.Forms.ImeMode のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Windows.Forms.ImeMode lblConfirm2_ImeMode {
            get {
                object obj = ResourceManager.GetObject("lblConfirm2.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   {X=21,Y=197} に類似した型 System.Drawing.Point のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Point lblConfirm2_Location {
            get {
                object obj = ResourceManager.GetObject("lblConfirm2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {Width=71, Height=12} に類似した型 System.Drawing.Size のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Size lblConfirm2_Size {
            get {
                object obj = ResourceManager.GetObject("lblConfirm2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   12 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int lblConfirm2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblConfirm2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   lblConfirm2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblConfirm2_Text {
            get {
                return ResourceManager.GetString("lblConfirm2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   False に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool lblConfirm2_Visible {
            get {
                object obj = ResourceManager.GetObject("lblConfirm2.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool lblTotalPrice_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblTotalPrice.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   [Font: Name=Microsoft YaHei UI, Size=18, Units=3, GdiCharSet=1, GdiVerticalFont=False] に類似した型 System.Drawing.Font のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Font lblTotalPrice_Font {
            get {
                object obj = ResourceManager.GetObject("lblTotalPrice.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   {X=588,Y=571} に類似した型 System.Drawing.Point のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Point lblTotalPrice_Location {
            get {
                object obj = ResourceManager.GetObject("lblTotalPrice.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {Width=122, Height=31} に類似した型 System.Drawing.Size のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Size lblTotalPrice_Size {
            get {
                object obj = ResourceManager.GetObject("lblTotalPrice.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   2 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int lblTotalPrice_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblTotalPrice.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   totalprice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblTotalPrice_Text {
            get {
                return ResourceManager.GetString("lblTotalPrice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   order_num に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string order_num_HeaderText {
            get {
                return ResourceManager.GetString("order_num.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int order_num_MinimumWidth {
            get {
                object obj = ResourceManager.GetObject("order_num.MinimumWidth", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool order_num_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("order_num.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   60 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int order_num_Width {
            get {
                object obj = ResourceManager.GetObject("order_num.Width", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   subtotal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string subtotal_HeaderText {
            get {
                return ResourceManager.GetString("subtotal.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool subtotal_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("subtotal.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   [Font: Name=Microsoft YaHei UI, Size=18, Units=3, GdiCharSet=1, GdiVerticalFont=False] に類似した型 System.Drawing.Font のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Font tboxTotalPrice_Font {
            get {
                object obj = ResourceManager.GetObject("tboxTotalPrice.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   {X=716,Y=603} に類似した型 System.Drawing.Point のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Point tboxTotalPrice_Location {
            get {
                object obj = ResourceManager.GetObject("tboxTotalPrice.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {Width=174, Height=38} に類似した型 System.Drawing.Size のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Size tboxTotalPrice_Size {
            get {
                object obj = ResourceManager.GetObject("tboxTotalPrice.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   3 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int tboxTotalPrice_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tboxTotalPrice.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Center に類似した型 System.Windows.Forms.HorizontalAlignment のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Windows.Forms.HorizontalAlignment tboxTotalPrice_TextAlign {
            get {
                object obj = ResourceManager.GetObject("tboxTotalPrice.TextAlign", resourceCulture);
                return ((System.Windows.Forms.HorizontalAlignment)(obj));
            }
        }
    }
}
