//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlexOrder {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Frm_C_Cart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Frm_C_Cart() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlexOrder.Frm_C_Cart", typeof(Frm_C_Cart).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [Font: Name=Microsoft YaHei UI, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False] に類似した型 System.Drawing.Font のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Font btnBack_Font {
            get {
                object obj = ResourceManager.GetObject("btnBack.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   {X=32,Y=362} に類似した型 System.Drawing.Point のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Point btnBack_Location {
            get {
                object obj = ResourceManager.GetObject("btnBack.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {Width=114, Height=60} に類似した型 System.Drawing.Size のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Size btnBack_Size {
            get {
                object obj = ResourceManager.GetObject("btnBack.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   1 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int btnBack_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnBack.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   btnBack に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnBack_Text {
            get {
                return ResourceManager.GetString("btnBack.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Font: Name=Microsoft YaHei UI, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False] に類似した型 System.Drawing.Font のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Font btnGoPay_Font {
            get {
                object obj = ResourceManager.GetObject("btnGoPay.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   {X=646,Y=362} に類似した型 System.Drawing.Point のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Point btnGoPay_Location {
            get {
                object obj = ResourceManager.GetObject("btnGoPay.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {Width=114, Height=60} に類似した型 System.Drawing.Size のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Size btnGoPay_Size {
            get {
                object obj = ResourceManager.GetObject("btnGoPay.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   1 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int btnGoPay_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnGoPay.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   btnGoPay に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnGoPay_Text {
            get {
                return ResourceManager.GetString("btnGoPay.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Font: Name=MS UI Gothic, Size=16, Units=3, GdiCharSet=1, GdiVerticalFont=False] に類似した型 System.Drawing.Font のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Font btnReset_Font {
            get {
                object obj = ResourceManager.GetObject("btnReset.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   {X=32,Y=12} に類似した型 System.Drawing.Point のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Point btnReset_Location {
            get {
                object obj = ResourceManager.GetObject("btnReset.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {Width=41, Height=39} に類似した型 System.Drawing.Size のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Size btnReset_Size {
            get {
                object obj = ResourceManager.GetObject("btnReset.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   5 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int btnReset_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnReset.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   ↺ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btnReset_Text {
            get {
                return ResourceManager.GetString("btnReset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {X=113,Y=12} に類似した型 System.Drawing.Point のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Point dgvCart_Location {
            get {
                object obj = ResourceManager.GetObject("dgvCart.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   51 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int dgvCart_RowHeadersWidth {
            get {
                object obj = ResourceManager.GetObject("dgvCart.RowHeadersWidth", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   {Width=614, Height=297} に類似した型 System.Drawing.Size のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Size dgvCart_Size {
            get {
                object obj = ResourceManager.GetObject("dgvCart.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   0 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int dgvCart_TabIndex {
            get {
                object obj = ResourceManager.GetObject("dgvCart.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   goods_image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string goods_image_HeaderText {
            get {
                return ResourceManager.GetString("goods_image.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int goods_image_MinimumWidth {
            get {
                object obj = ResourceManager.GetObject("goods_image.MinimumWidth", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool goods_image_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("goods_image.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   150 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int goods_image_Width {
            get {
                object obj = ResourceManager.GetObject("goods_image.Width", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   goods_name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string goods_name_HeaderText {
            get {
                return ResourceManager.GetString("goods_name.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int goods_name_MinimumWidth {
            get {
                object obj = ResourceManager.GetObject("goods_name.MinimumWidth", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool goods_name_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("goods_name.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   140 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int goods_name_Width {
            get {
                object obj = ResourceManager.GetObject("goods_name.Width", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   goods_price に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string goods_price_HeaderText {
            get {
                return ResourceManager.GetString("goods_price.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int goods_price_MinimumWidth {
            get {
                object obj = ResourceManager.GetObject("goods_price.MinimumWidth", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool goods_price_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("goods_price.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   140 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int goods_price_Width {
            get {
                object obj = ResourceManager.GetObject("goods_price.Width", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool lblTotalPrice_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblTotalPrice.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   [Font: Name=MS UI Gothic, Size=16, Units=3, GdiCharSet=1, GdiVerticalFont=False] に類似した型 System.Drawing.Font のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Font lblTotalPrice_Font {
            get {
                object obj = ResourceManager.GetObject("lblTotalPrice.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   {X=490,Y=326} に類似した型 System.Drawing.Point のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Point lblTotalPrice_Location {
            get {
                object obj = ResourceManager.GetObject("lblTotalPrice.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {Width=98, Height=22} に類似した型 System.Drawing.Size のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Size lblTotalPrice_Size {
            get {
                object obj = ResourceManager.GetObject("lblTotalPrice.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   2 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int lblTotalPrice_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblTotalPrice.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   totalprice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblTotalPrice_Text {
            get {
                return ResourceManager.GetString("lblTotalPrice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool lblYen_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblYen.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   [Font: Name=MS UI Gothic, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False] に類似した型 System.Drawing.Font のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Font lblYen_Font {
            get {
                object obj = ResourceManager.GetObject("lblYen.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   {X=606,Y=332} に類似した型 System.Drawing.Point のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Point lblYen_Location {
            get {
                object obj = ResourceManager.GetObject("lblYen.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {Width=15, Height=16} に類似した型 System.Drawing.Size のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Size lblYen_Size {
            get {
                object obj = ResourceManager.GetObject("lblYen.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   4 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int lblYen_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblYen.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   \ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblYen_Text {
            get {
                return ResourceManager.GetString("lblYen.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sale_num に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string sale_num_HeaderText {
            get {
                return ResourceManager.GetString("sale_num.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int sale_num_MinimumWidth {
            get {
                object obj = ResourceManager.GetObject("sale_num.MinimumWidth", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   True に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool sale_num_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("sale_num.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   False に類似した型 System.Boolean のローカライズされたリソースを検索します。
        /// </summary>
        public static bool tboxTotalPrice_Enabled {
            get {
                object obj = ResourceManager.GetObject("tboxTotalPrice.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   {X=627,Y=332} に類似した型 System.Drawing.Point のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Point tboxTotalPrice_Location {
            get {
                object obj = ResourceManager.GetObject("tboxTotalPrice.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   {Width=100, Height=19} に類似した型 System.Drawing.Size のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Size tboxTotalPrice_Size {
            get {
                object obj = ResourceManager.GetObject("tboxTotalPrice.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   3 に類似した型 System.Int32 のローカライズされたリソースを検索します。
        /// </summary>
        public static int tboxTotalPrice_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tboxTotalPrice.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
